---
title: "Sweden Variables Macroeconomic"
author: "Henri Makika"
date: "Julho 10, 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE,
                      fig.width = 12, fig.height = 8)
```

## Introduction


```{r}
library(readxl)
library(vars)
library(urca)
library(lmtest)
library(MASS)
library(TSA)
```

## Données


```{r}
Donnee = read_excel("~/Videos/Unicamp_IE 2019/HO:236A Times Series/Ensaio/Dados_Sweden.xls")
Dados = ts(Donnee[,2:4], start = c(2012, 1), end = c(2018, 12), frequency = 12)
head(Dados)
```

## Plot


```{r}
plot((Dados[,1]), main = "Masse monétaire M3", ylab = "M3 Suède", xlab = "")
grid()
plot((Dados[,2]), main = "Taux de chômage", ylab = "Chômage Suède", xlab = "")
grid()
plot((Dados[,3]), main = "Production Totale", ylab = "Production Suède", xlab = "")
grid()
```

## Test RU

### Dickey Fuller

```{r}
df = ur.df(Dados, type = "trend", lags = 12, selectlags = "AIC")
```




## Ordre du modèle 


```{r}
ordre = VARselect(diff(Dados[,1:3]), lag.max = 6, type = "const")

ordre
```

## Estimation du modèle


```{r}
modele.est = VAR(diff(Dados[,1:3]), type = "const", p = 2)

modele.est
```

## Test RU


```{r}
var.arch = arch.test(modele.est)

print(var.arch)
```



```{r}
var.norm = normality.test(modele.est)

print(var.norm)
```


